### ISSUE TITLE
3000 SDI2

### ISSUE THREAD

**Issue by fredhandle** [sanjay900/solution3000-home-assistant#3]
The 2000/3000 were derived in Bosch China from the AU developed 800 series Solution Alarms. Utilising the BUS protocol SDI2. There was enough of the automation protocol in the 3000 to allow the RSC+ app to work but not the complete automation protocol. This is why the B450 works on the 3000 similar to the B and G series out of the US. This explains why there is confusion between Bosch AU and US support teams. If Bosch do extend the automation protocol fully it would be worth pursuing the NDA for the complete spec. I do have this document. 
Output types on the 3000 are defined differently in the 3000 to the US controllers and of the 40+ types not all are defined as controllable. The PIN code authority also needs to be defined as an Admin to operate outputs with the 3000.

**Comment by sanjay900** [comment]
The one thing i was trying to work out, is how do you tell if the alarm is currently going off?
Outputs would also be nice to get working but im nowhere near as worried about that right now
I was told i would be given an NDA to sign once the new protocol was designed, but its been a while and i have not heard anything yet.

**Comment by fredhandle** [comment]
I wouldn’t hold your breath. There were bugs to be resolved in v2 firmware that only took 2+ years to fix. 
Other products I have worked with using the automation protocol poll the status of outputs and inputs. By default output 1 is "siren running" if you can monitor the status.

**Comment by EHylands** [comment]
> I wouldn’t hold your breath. There were bugs to be resolved in v2 firmware that only took 2+ years to fix. 
> 
> Other products I have worked with using the automation protocol poll the status of outputs and inputs. By default output 1 is "siren running" if you can monitor the status.

I was able to pool on my B Panel using the following protocol 1.23 call:

Mode2ReqAlarmMemorySummary [0x08]
Mode2ReqAlarmMemoryDetail [0x023]

You think those two function will work en Solution 3000 ?

**Comment by sanjay900** [comment]
Works perfectly fine, thank you very much!
