### ISSUE TITLE
Support for Solution 2000?

### ISSUE THREAD

**Issue by buzurk26** [sanjay900/solution3000-home-assistant#7]
Hi, Will this work for solution 2000?

Got this panel with the B426-M Module and RSC+ all setup and working but really want HAS integration

**Comment by sanjay900** [comment]
never tried, give it a try and let me know. I only have a 3000, hence that was all it was tested with.

**Comment by sanjay900** [comment]
Did this work on your 2000? Im working on a new addon for this that should be more stable, but i was curious if this one did work on your 2000?

**Comment by buzurk26** [comment]
Hi @sanjay900 

Yeah still no luck with the Solution 2000, it even led me to purchasing a new IP board as mine was an older revision, i got the new board version of theB425-m board - no luck, super keen to get this working and happy to test any new versions you have and assist with any other info that might help to get this working

Greatly appreciate your efforts on this :)

**Comment by sanjay900** [comment]
any difference with this?
https://github.com/sanjay900/bosch-alarm-homeassistant

**Comment by buzurk26** [comment]
Will give it a go

Do i just go into HACs and 'Redownload' ? or do i need to pull the files off github and upload them

**Comment by sanjay900** [comment]
you can add that as a repo to HACS, its a totally seperate integration

**Comment by buzurk26** [comment]
All installed, getting hung up on here
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/35dfe374-aabb-4be2-8a26-5a23326a6429)

**Comment by buzurk26** [comment]
Ok, installed, failed to connect ;(
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/a4e38c62-e48c-4762-b553-0c29cd99e23a)

**Comment by sanjay900** [comment]
can you send a copy of the error from your log?
and did you use the right port and ip and the passcode you use for RSC+?
port is likely 7700

**Comment by buzurk26** [comment]
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/afe7e346-7f45-402e-a28a-6fb880abc66b)
IP is the B426-M, Yeah same pin as the app, not logged into the app either.

Nothing in HAS logs, the failed to connect comes up almost instantly too

**Comment by buzurk26** [comment]
Is there another log file?

**Comment by sanjay900** [comment]
What log are you looking at?

**Comment by sanjay900** [comment]
id expect something to show up in the home assistant core logs in home assistant

**Comment by sanjay900** [comment]
out of curiousity, if you have access to a linux / mac machine, can you try running the following?
`echo -e "\x01\x01\x01" | openssl s_client -connect 172.25.0.1:7700 -quiet | xxd`

**Comment by buzurk26** [comment]
Yeah i can spin one up quickly and test

**Comment by sanjay900** [comment]
for comparison, on my working panel i see this:
```
echo -e "\x01\x01\x01" | openssl s_client -connect 192.168.0.96:7700 -quiet | xxd                                                                                                                                                                                                                                                                                   0|INT|INT ✘
Can't use SSL_get_servername
depth=0 C = US, ST = NY, L = Fairport, O = Bosch Security Systems, OU = BU Intrusion, CN = US-1B, emailAddress = info@us.bosch.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = NY, L = Fairport, O = Bosch Security Systems, OU = BU Intrusion, CN = US-1B, emailAddress = info@us.bosch.com
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 C = US, ST = NY, L = Fairport, O = Bosch Security Systems, OU = BU Intrusion, CN = US-1B, emailAddress = info@us.bosch.com
verify error:num=10:certificate has expired
notAfter=Apr 15 16:54:19 2022 GMT
verify return:1
depth=0 C = US, ST = NY, L = Fairport, O = Bosch Security Systems, OU = BU Intrusion, CN = US-1B, emailAddress = info@us.bosch.com
notAfter=Apr 15 16:54:19 2022 GMT
verify return:1
00000000: 010f fe21 0502 0000 0203 0000 0216 0000  ...!............
```

**Comment by buzurk26** [comment]
Thanks for that, seems my module has stopped responding on port 7700, i cant find a way to reboot it either from web ui, might have to power cycle when im back

**Comment by sanjay900** [comment]
had one guy with a similar problem on their 3000, they ended up just resetting their panel via a-link to get things working, but it would be interesting to compare your settings to https://github.com/EHylands/homebridge-boschcontrolpanel_bgseries/issues/1#issuecomment-1317668314

**Comment by buzurk26** [comment]
Oh yeah i can do that, will try that now

**Comment by buzurk26** [comment]
I have connected to it via a-link, no reset option i can find - damn

**Comment by sanjay900** [comment]
mind doing a comparison between your settings and those screenshots in that comment link?

**Comment by buzurk26** [comment]
Sure can will get that and post it up soon

**Comment by buzurk26** [comment]
After alot of mucking around i got it to work!!!!!!!!!! thank you so much, been wanting this alarm in HA for over 3 years 
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/742a73b7-ec12-4dd2-b8f0-7ae83b39d050)

**Comment by sanjay900** [comment]
awesome!

**Comment by sanjay900** [comment]
What did you need to change?

**Comment by buzurk26** [comment]
Back tracking through that now, one of those changed many situations so looking to see what made it work

one issue, maybe design is if i press ARM from HA the panel starts beeping which is great, but if i press home, or disarm it doesn't stop beeping it continues to want to arm

Ive not let it arm yet, too many home and will set it off, but assume maybe if i let it fully arm then press disarm it will work?

Do i need to wait for it to fully arm first? I notice there is no "pin" to disarm it?

**Comment by sanjay900** [comment]
the disarm button should work at any time, how odd. In terms of a pin, ill need to add support for pins since the integration currently doesn't have a pin built in

**Comment by sanjay900** [comment]
can i see your log file?

**Comment by buzurk26** [comment]
It worked the very first time, i pressed it not long after and it stopped
Subsequent times have not worked

![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/74d4fc9e-cb1f-485c-a392-fe059154f6eb)
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/9b42eb05-11f9-4095-b592-bc661763ca8f)
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/b7c021d5-2f3d-4a6e-bad9-46e4154302fc)

**Comment by buzurk26** [comment]
Just tried it again and it worked now, odd

**Comment by buzurk26** [comment]
Notice the RSC+ app dosnt work at all now either, assume you can only have one or the other maybe

**Comment by sanjay900** [comment]
Yeah, sadly the panel only lets one device be connected at a time
If you did have the app open, that might be why things are acting strangly?

**Comment by buzurk26** [comment]
i had a-link open still, maybe that caused it

The app dosnt work at all now, if HAS is reliable i can setup notifications there anyway

Do you have a states list for when alarm is triggered?

**Comment by buzurk26** [comment]
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/7e1234b3-f3a1-4492-8c70-0b38e9616bb7)

**Comment by sanjay900** [comment]
Yeah when it's triggered it should just be a state of triggered

**Comment by buzurk26** [comment]
Oh cool ill base an automation off that.

**Comment by buzurk26** [comment]
Thanks again, Do you do much with automations?

Think this would work, disarm the alarm automatically if my phone enters the "home" zone via gps

> `alias: Alarm - Disarm when home
> description: ""
> trigger:
>   - platform: device
>     device_id: 94c8b76a01a37943fb880a088d3b2372
>     domain: device_tracker
>     entity_id: device_tracker.sm_g998b
>     type: enters
>     zone: zone.home
> condition:
>   - condition: state
>     entity_id: alarm_control_panel.area1
>     state: armed_away
> action:
>   - service: alarm_control_panel.alarm_disarm
>     data: {}
>     target:
>       entity_id: alarm_control_panel.area1
> mode: single
> `

**Comment by sanjay900** [comment]
Yeah i think that would work

**Comment by sanjay900** [comment]
There is also a state of "pending" for when the alarm detects movement and is about to transition into a triggered state

**Comment by sanjay900** [comment]
Heres a list of the states that the panel can go into:
- triggered
- disarmed
- arming
- pending
- armed_home
- armed_away

**Comment by buzurk26** [comment]
Awesome, Thank you - ill create some cool automations

the motion sensors will be handy too

**Comment by buzurk26** [comment]
Hey Mate, 

Just checking in, its been working well, from time to time its reporting as disconnected for a few minutes though only happened a couple of times since installing

HACs told me its ready for an update, do i update as they come out?
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/5a467897-6f7f-438c-a669-c2987be788e0)


The integration needs an icon :-P
![image](https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/fc7ee9ab-78d8-49f8-85c6-77dee531744c)

**Comment by sanjay900** [comment]
yeah so ive still been adding features as time has been going on, though the last little bit i was just messing with trying to get someones AMAX panel going. Ive since added support for arming codes, and ill be adding in history support soon

**Comment by sanjay900** [comment]
Seems like sometimes the panel just times out ocassionally, but at least it reconnects alright

**Comment by buzurk26** [comment]
Oh nice might do the update then

**Comment by sanjay900** [comment]
Gonna try and get history implemetned as well today if i can

**Comment by sanjay900** [comment]
Im going to close this issue, as this integration is being deprecated in favour of https://github.com/mag1024/bosch-alarm-homeassistant.

**Comment by buzurk26** [comment]
@sanjay900  - Oh! Should i uninstall and changeover to that one? Im using the new one you gave me https://github.com/sanjay900/bosch-alarm-homeassistant

i did have a large disconnect last night too
<img width="376" alt="image" src="https://github.com/sanjay900/solution3000-home-assistant/assets/39994663/98afbe5d-9ce1-4c29-b9a8-79bf541cf9e3">

**Comment by sanjay900** [comment]
Yeah this one should be more stable

**Comment by buzurk26** [comment]
No worries , so just remove all this from ha and hacs then add that repo
and install?

**Comment by sanjay900** [comment]
Yeah exactly
